@ExpenseTracker_Api_HostAddress = http://localhost:5017

### Get All Transactions
GET {{ExpenseTracker_Api_HostAddress}}//api/Transactions
Accept: application/json

### Get Transaction By Id
GET {{ExpenseTracker_Api_HostAddress}}//api/Transactions/1

### Create new Expense transaction
POST {{ExpenseTracker_Api_HostAddress}}/api/Transactions
Content-Type: application/json

{
  "description": "Coffee",
  "amount": 4.50,
  "type": "Expense",
  "category": "Food",
  "date": "2026-06-06"
}

### Create new income transaction
POST {{ExpenseTracker_Api_HostAddress}}/api/transactions
Content-Type: application/json

{
  "description": "Freelance payment",
  "amount": 300,
  "type": "Income",
  "category": "Work",
  "date": "2026-06-06"
}

### Update Transaction
PUT {{ExpenseTracker_Api_HostAddress}}/api/Transactions/1
Content-Type: application/json

{
  "description": "Monthly Salary",
  "amount": 2600,
  "type": "Income",
  "category": "Job",
  "date": "2026-06-06"
}

### Delete Transaction
DELETE {{ExpenseTracker_Api_HostAddress}}/api/Transactions/2
Accept: application/json

/////////////////////// Categories //////////////////

### Get all categories
GET {{ExpenseTracker_Api_HostAddress}}/api/Categories
Accept: application/json

### Get category by id
GET {{ExpenseTracker_Api_HostAddress}}/api/Categories/1
Accept: application/json

### Create food category
POST {{ExpenseTracker_Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "Food"
}

### Create salary category
POST {{ExpenseTracker_Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "Salary"
}

### Create transport category
POST {{ExpenseTracker_Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "Transport"
}

### Update category
PUT {{ExpenseTracker_Api_HostAddress}}/api/Categories/1
Content-Type: application/json

{
  "Name": "Groceries"
}

### Delete category
DELETE {{ExpenseTracker_Api_HostAddress}}/api/Categories/2
Accept: application/json