@ExpenseTracker_Api_HostAddress = http://localhost:5017

### Get monthly summary
GET {{ExpenseTracker_Api_HostAddress}}/api/reports/monthly-summary?year=2026&month=6
Accept: application/json

### Get transactions with pagination
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?pageNumber=1&pageSize=5
Accept: application/json


### Get second page
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?pageNumber=2&pageSize=5
Accept: application/json


### Sort by amount ascending
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?sortBy=amount&sortDirection=asc
Accept: application/json


### Sort by amount descending
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?sortBy=amount&sortDirection=desc
Accept: application/json


### Filter, sort, and paginate together
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?type=Expense&categoryId=1&sortBy=amount&sortDirection=desc&pageNumber=1&pageSize=10
Accept: application/json

### Get All Transactions
GET {{ExpenseTracker_Api_HostAddress}}//api/Transactions
Accept: application/json

### Filter by expense
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?type=Expense
Accept: application/json


### Filter by income
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?type=Income
Accept: application/json


### Filter by category
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?categoryId=1
Accept: application/json


### Filter by date range
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?fromDate=2026-06-01&toDate=2026-06-30
Accept: application/json


### Filter by type and category
GET {{ExpenseTracker_Api_HostAddress}}/api/transactions?type=Expense&categoryId=2
Accept: application/json

### Get Transaction By Id
GET {{ExpenseTracker_Api_HostAddress}}//api/Transactions/1

### Create new Expense transaction
POST {{ExpenseTracker_Api_HostAddress}}/api/Transactions
Content-Type: application/json

{
  "description": "Bus Ticket",
  "amount": 23,
  "type": "Expense",
  "categoryId": 3,
  "date": "2026-06-06"
}

### Create new income transaction
POST {{ExpenseTracker_Api_HostAddress}}/api/transactions
Content-Type: application/json

{
  "description": "Freelance payment",
  "amount": 300,
  "type": "Income",
  "categoryId": 1002,
  "date": "2026-06-06"
}

### Update Transaction
PUT {{ExpenseTracker_Api_HostAddress}}/api/Transactions/1
Content-Type: application/json

{
  "description": "Monthly Salary",
  "amount": 2600,
  "type": "Income",
  "categoryId": 1,
  "date": "2026-06-06"
}

### Delete Transaction
DELETE {{ExpenseTracker_Api_HostAddress}}/api/Transactions/2
Accept: application/json

/////////////////////// Categories //////////////////

### Get all categories
GET {{ExpenseTracker_Api_HostAddress}}/api/Categories
Accept: application/json

### Get category by id
GET {{ExpenseTracker_Api_HostAddress}}/api/Categories/1
Accept: application/json

### Create food category
POST {{ExpenseTracker_Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "Gambling"
}

### Create salary category
POST {{ExpenseTracker_Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "Salary"
}

### Create transport category
POST {{ExpenseTracker_Api_HostAddress}}/api/Categories
Content-Type: application/json

{
  "Name": "Gaming"
}

### Update category
PUT {{ExpenseTracker_Api_HostAddress}}/api/Categories/2002
Content-Type: application/json

{
  "Name": "TT"
}

### Delete category
DELETE {{ExpenseTracker_Api_HostAddress}}/api/Categories/1002
Accept: application/json